name: ml-api
channels:
  - conda-forge
  - defaults
dependencies:
  - dvc=3.22.1
  - mlflow=2.7.1
  - ipython=8.15.0
  - notebook=7.0.4
  - jupyterlab=4.0.6
  - matplotlib=3.8.0
  - pandas=2.1.1
  - seaborn=0.13.0
  - git=2.40.1
  - pip=23.2.1
  - pandas=2.1.1
  - scikit-learn=1.3.1
  - pytest=7.4.2
  - requests=2.31.0
  - fastapi=0.104.0
  - uvicorn=0.23.2
  - gunicorn=21.2.0
  - black=23.10.0
  - pip:
      - wandb==0.15.11
